# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98454925f293671edbaadafc8d200d11669d2e4161a814eb1dd27873df6ccac72b01ef3b090d3540fabace03d2784ebe1f2ef345e2c67174a2f79c4031dd3de4

test:
  secret_key_base: f204bd6698f89a7413aa20c28824cfdcd4fd781380055f7f35e52972f06a8540924ba3cd3502a10d61824f24474f8baf3a2468c4dc083dafed60a73fec072dbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
